# theme: jekyll-theme-minimal
remote_theme: mmistakes/minimal-mistakes
permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

include: ["_pages"]
